apiVersion: v1
kind: Service
metadata:
  name: {{ include "optimize.fullname" . }}
  labels: {{- include "optimize.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.global.annotations}}
    {{- toYaml .Values.global.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.service.annotations}}
    {{- toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    name: http
    targetPort: 8090
    protocol: TCP
  - port: {{ .Values.service.managementPort }}
    name: management
    targetPort: 8092
    protocol: TCP
  selector:
    {{- include "optimize.matchLabels" . | nindent 4 }}
