{{- if eq (include "camunda-bpm-platform.h2DatabaseIsUsed" .) "true" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "camunda-bpm-platform.fullname" . }}-database-h2
  labels:
    {{- include "camunda-bpm-platform.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
{{- end }}
