{{- $h2DatabaseIsUsed := eq (include "camunda-bpm-platform.h2DatabaseIsUsed" .) "true" -}}
{{- $noCredentialsSecretIsProvided := (empty .Values.database.credentialsSecretName) -}}
{{- if and $h2DatabaseIsUsed $noCredentialsSecretIsProvided -}}
# This secret is used for ephemeral H2 database only.
# Create your own secret for external databases like PostgreSQL.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "camunda-bpm-platform.fullname" . }}
  labels:
    {{- include "camunda-bpm-platform.labels" . | nindent 4 }}
stringData:
  # From Camunda offcial docs:
  # https://docs.camunda.org/manual/latest/installation/full/tomcat/pre-packaged/#accessing-the-h2-console
  DB_PASSWORD: "sa"
  DB_USERNAME: "sa"
{{- end }}
